"use client";

import Link from 'next/link';
import { Zap, Target, Brain, Globe, Shield, Users, ArrowRight, BarChart3, Database, Search, CheckCircle2 } from 'lucide-react';
import Footer from '@/components/Footer';
import CTA from '@/components/CTA';
import { motion } from 'framer-motion';

export default function AboutPage() {
    return (
        <div className="min-h-screen bg-white text-black font-sans selection:bg-black selection:text-white">
            {/* Navbar */}
            <nav className="border-b border-black/5 bg-white/80 backdrop-blur-xl sticky top-0 z-50">
                <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-3 group">
                        <motion.div
                            whileHover={{ rotate: 10, scale: 1.1 }}
                            className="w-10 h-10 rounded-xl bg-black flex items-center justify-center shadow-lg shadow-black/10"
                        >
                            <Zap className="h-6 w-6 text-white fill-white" />
                        </motion.div>
                        <span className="font-bold text-2xl tracking-tighter text-black">Tracintel</span>
                    </Link>
                    <div className="flex items-center gap-8 text-sm font-bold">
                        <Link href="/pricing" className="text-black/50 hover:text-black transition-colors">Pricing</Link>
                        <Link href="/careers" className="text-black/50 hover:text-black transition-colors">Careers</Link>
                    </div>
                </div>
            </nav>

            {/* Massive Hero Section */}
            <header className="py-32 md:py-56 px-6 bg-white border-b border-black/5">
                <div className="max-w-5xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8 }}
                    >
                        <div className="text-[10px] font-mono uppercase tracking-[0.3em] text-black/30 mb-10 border-l border-black pl-5 font-bold">// THE TRACINTEL MANIFESTO</div>
                        <h1 className="text-7xl md:text-[120px] font-bold tracking-tighter text-black mb-16 leading-[0.85]">
                            Intelligence for <br /><span className="italic text-black/40">The AI Economy.</span>
                        </h1>
                        <p className="text-2xl md:text-4xl text-black/60 leading-tight font-light max-w-4xl">
                            Traditional search is dying. The blue links of the 2000s are being replaced by generative synthesis. Tracintel was built to help global brands navigate this shift from keywords to authority.
                        </p>
                    </motion.div>
                </div>
            </header>

            {/* The Problem Deep Dive */}
            <section className="py-32 md:py-48 px-6">
                <div className="max-w-4xl mx-auto space-y-16">
                    <h2 className="text-5xl md:text-7xl font-bold tracking-tighter italic">The Search Renaissance</h2>
                    <div className="text-xl md:text-2xl text-black/50 leading-relaxed space-y-12 font-light">
                        <p>
                            For two decades, Digital Marketing was defined by Google. We optimized for crawlers, keywords, and backlinks. We treated the search box as a gateway to a destination. But in the age of Large Language Models (LLMs), the "search result" is no longer a list of URLs—it is a comprehensive, synthesized answer generated by models like GPT-4, Claude 3.5, and Gemini 1.5 Pro.
                        </p>
                        <p>
                            When a customer asks ChatGPT, "What is the best enterprise security platform for a fintech startup?", the AI doesn't just rank websites. It scans its internal weights—trained on petabytes of professional data—and makes a probabilistic recommendation. If your brand isn't part of that recommendation, you don't exist in that customer's journey.
                        </p>
                        <p className="text-black font-medium italic">
                            This is Generative Engine Optimization (GEO). At Tracintel, we've spent thousands of hours reverse-engineering the authority signals that drive AI citations. We've found that LLMs prioritize semantic density, source reliability, and cross-contextual validation over legacy SEO metrics.
                        </p>
                    </div>
                </div>
            </section>

            {/* The Tracintel Methodology */}
            <section className="py-32 px-6 bg-soft-gray border-y border-black/5">
                <div className="max-w-7xl mx-auto">
                    <div className="mb-32 text-center">
                        <h2 className="text-6xl md:text-8xl font-bold tracking-tighter mb-8 italic">The Methodology</h2>
                        <p className="text-2xl text-black/40 max-w-2xl mx-auto font-light leading-relaxed">Our proprietary framework for auditing and optimizing brand visibility in the generative landscape.</p>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        {/* Phase 1: Scan */}
                        <div className="bento-card p-12 space-y-8 hover:scale-[1.02] transition-transform">
                            <div className="w-16 h-16 rounded-2xl bg-black flex items-center justify-center text-white shadow-xl shadow-black/20">
                                <Search className="h-8 w-8" />
                            </div>
                            <h3 className="text-4xl font-bold tracking-tighter italic">01. Scan</h3>
                            <p className="text-xl text-black/50 leading-relaxed font-light">
                                We begin by querying models like GPT-4, Claude, and Gemini using thousands of probabilistic prompt variations. We look for **semantic proximity**—how closely AI associates your brand with target categories and pain points.
                            </p>
                            <div className="pt-8 border-t border-black/5">
                                <ul className="space-y-4 text-xs font-mono uppercase tracking-widest text-black/40">
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Prompt Simulation</li>
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Response Capturing</li>
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Persona Testing</li>
                                </ul>
                            </div>
                        </div>

                        {/* Phase 2: Analyze */}
                        <div className="bento-card p-12 space-y-8 hover:scale-[1.02] transition-transform">
                            <div className="w-16 h-16 rounded-2xl bg-black flex items-center justify-center text-white shadow-xl shadow-black/20">
                                <BarChart3 className="h-8 w-8" />
                            </div>
                            <h3 className="text-4xl font-bold tracking-tighter italic">02. Analyze</h3>
                            <p className="text-xl text-black/50 leading-relaxed font-light">
                                Responses are passed through our NLP engine to calculate **Citation Affinity**. We audit "reputation drift"—identifying where models have outdated or hallucinatory data about your company.
                            </p>
                            <div className="pt-8 border-t border-black/5">
                                <ul className="space-y-4 text-xs font-mono uppercase tracking-widest text-black/40">
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Affinity Scoring</li>
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Drift Auditing</li>
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Origin Analysis</li>
                                </ul>
                            </div>
                        </div>

                        {/* Phase 3: Signal */}
                        <div className="bento-card p-12 space-y-8 hover:scale-[1.02] transition-transform">
                            <div className="w-16 h-16 rounded-2xl bg-black flex items-center justify-center text-white shadow-xl shadow-black/20">
                                <Database className="h-8 w-8" />
                            </div>
                            <h3 className="text-4xl font-bold tracking-tighter italic">03. Signal</h3>
                            <p className="text-xl text-black/50 leading-relaxed font-light">
                                We provide high-precision "Content Seeds"—optimized technical documentation and PR designed to be indexed by training crawlers before the next model epoch begins.
                            </p>
                            <div className="pt-8 border-t border-black/5">
                                <ul className="space-y-4 text-xs font-mono uppercase tracking-widest text-black/40">
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Seed Generation</li>
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Schema Deployment</li>
                                    <li className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-black" /> Epoch Tuning</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Why Training Data Matters */}
            <section className="py-32 md:py-48 px-6 bg-white overflow-hidden">
                <div className="max-w-5xl mx-auto">
                    <h2 className="text-5xl md:text-7xl font-bold tracking-tighter mb-16 italic">Auditing the Foundation</h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-24 items-center">
                        <div className="text-xl text-black/50 leading-relaxed space-y-8 font-light">
                            <p>
                                Modern AI models are only as good as the data they consume. If your corporate narrative is inconsistent across the web, models will produce fragmented recommendations.
                            </p>
                            <p>
                                We help brands audit their footprint through the lens of a LLM training crawler. We identify high-signal sources—technical documentations, peer-reviewed journals, and technical wikis—that carry the most weight in model training.
                            </p>
                            <p className="text-black font-medium italic">
                                Our mission is to ensure that when the next trillion-parameter model is trained, it understands your company’s value proposition with absolute clarity.
                            </p>
                        </div>
                        <div className="relative">
                            <div className="absolute inset-0 bg-black/5 rounded-full blur-3xl" />
                            <div className="relative bento-card p-12 bg-white/50 backdrop-blur-xl">
                                <div className="space-y-6 font-mono text-[10px] uppercase tracking-widest">
                                    <div className="flex justify-between items-center text-black/20 border-b border-black/5 pb-4">
                                        <span>SIGNAL_QUERY_049</span>
                                        <span>STATUS: AUDITING</span>
                                    </div>
                                    <div className="text-black space-y-4">
                                        <p>&gt; scanning_training_origins...</p>
                                        <p>&gt; found_high_weight_doc: "WHITE_PAPER_2025"</p>
                                        <p>&gt; semantic_alignment: 0.94</p>
                                        <p>&gt; citation_probability: +14.2%</p>
                                        <p className="animate-pulse text-black/40">&gt; generating_content_seeds...</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* The Team / Future Section */}
            <section className="py-32 px-6 bg-black text-white">
                <div className="max-w-6xl mx-auto">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-32 items-center">
                        <div>
                            <h2 className="text-6xl md:text-8xl font-bold tracking-tighter mb-10 leading-tight italic">The Future</h2>
                            <p className="text-2xl text-white/50 mb-8 leading-relaxed font-light">
                                Tracintel was founded by a collective of researchers, linguists, and engineers. We saw that while the world was obsessing over *using* AI, no one was helping brands solve the problem of *being* AI-visible.
                            </p>
                            <p className="text-2xl text-white/50 mb-16 leading-relaxed font-light">
                                Based in SF and London, we are working at the intersection of information theory and market intelligence.
                            </p>
                            <div className="flex gap-16">
                                <div>
                                    <div className="text-5xl font-bold mb-2">50M+</div>
                                    <div className="text-[10px] font-mono uppercase text-white/20 tracking-widest font-bold">Prompts Scanned</div>
                                </div>
                                <div>
                                    <div className="text-5xl font-bold mb-2">12</div>
                                    <div className="text-[10px] font-mono uppercase text-white/20 tracking-widest font-bold">Models Audited</div>
                                </div>
                            </div>
                        </div>
                        <div className="grid grid-cols-2 gap-6">
                            <div className="h-80 rounded-3xl bg-white/5 border border-white/10 flex items-center justify-center grayscale opacity-30 hover:grayscale-0 hover:opacity-100 transition-all cursor-crosshair">
                                <span className="text-[10px] font-mono text-white/20 uppercase tracking-[0.4em] rotate-90">VISION</span>
                            </div>
                            <div className="h-80 rounded-3xl bg-white/5 border border-white/10 flex items-center justify-center grayscale opacity-30 hover:grayscale-0 hover:opacity-100 transition-all cursor-crosshair mt-16">
                                <span className="text-[10px] font-mono text-white/20 uppercase tracking-[0.4em] rotate-90">RIGOR</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <CTA />
            <Footer />
        </div>
    );
}
